image: ubuntu

#before_script:
#  - GRADLE_USER_HOME="$(pwd)/.gradle"
#  - export GRADLE_USER_HOME

Build:
  stage: build
  script:
    - echo "$USER, $UID, $(groups), $SHELL, $(uname -a), $(lsb_release -a) $PWD:"; ls -A

    - apt update && apt install -y opam && opam init -y
    - cd CAMLNES; opam switch -y create .
    - eval $(opam env)
    - dune build
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#    paths:
#      - build
#      - .gradle

Test:
  stage: test
  script: date
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: pull
#    paths:
#      - build
#x      - .gradle

#deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
